[project]
name = "financebro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "pydantic>=2.10.4",
    "ruff>=0.6.5",
    "yfinance>=0.2.66",
]
